var settings = 
{"drivers":[
  {"name":"MiTV", 
  "manufacturer":"Xiaomi",
  "buttons":{
    "CURSOR LEFT": {"label":"", "type":"http-get", "command":"http://192.168.1.24/YamahaExtendedControl/v1/main/setPower?power=on", "expectedresult":"{\"response_code\":0}", "fallbackbutton":""},
    "CURSOR RIGHT": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "CURSOR UP": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "CURSOR DOWN": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "CURSOR ENTER": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "POWER ON": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "POWER OFF": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "VOLUME UP": {"label":"", "type":"slidercontrol", "slidername":"VOLUME", "step":"5"},
    "VOLUME DOWN": {"label":"", "type":"slidercontrol", "slidername":"VOLUME", "step":"-5"},
    "MUTE TOGGLE": {"label":"", "type":"http-get", "commands":["http://192.168.1.24/YamahaExtendedControl/v1/main/setMute?enable=true","http://192.168.1.24/YamahaExtendedControl/v1/main/setMute?enable=false"], "expectedresult":"{\"response_code\":0}", "fallbackbutton":""},
    "DIGIT 0": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "DIGIT 1": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "DIGIT 2": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "DIGIT 3": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "DIGIT 4": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "DIGIT 5": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "DIGIT 6": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "DIGIT 7": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "DIGIT 8": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "DIGIT 9": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "FUNCTION RED": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "FUNCTION GREEN": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "FUNCTION YELLOW": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "FUNCTION BLUE": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "MENU": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "BACK": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "GUIDE": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "CHANNEL UP": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "CHANNEL DOWN": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "PLAY": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "PAUSE": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "STOP": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "REVERSE": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "FORWARD": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "PREVIOUS": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "NEXT": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "SKIP SECONDS BACKWARD": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "SKIP SECONDS FORWARD": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "MY RECORDING": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "RECORD": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "LIVE": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT HDMI 1": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT HDMI 2": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT HDMI 3": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT HDMI 4": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT HDMI 5": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT HDMI 6": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT HDMI 7": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT HDMI 8": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT VGA 1": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT VGA 2": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT VGA 3": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT SCART 1": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT SCART 2": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
    "INPUT SCART 3": {"label":"", "type":"", "command":"", "expectedresult":"", "fallbackbutton":""},
  },
  "sliders":{
    "VOLUME": {"label":"", "min" : 0, "max" : 161, "unit" : "db", "type":"http-get", "command":"http://192.168.1.24/YamahaExtendedControl/v2/main/setVolume?volume=", "statuscommand":"http://192.168.1.24/YamahaExtendedControl/v2/main/getStatus", "jpathstatus":"$.volume", "expectedresult":"{\"response_code\":0}", "fallbackbutton":""},
  }
}],          

   
//"imagesurl": "http://192.168.1.11:3000/store/"
"imagesurl": "https://raw.githubusercontent.com/jac459/NeeoHueDriver/master/Resources/"
}
  
module.exports = settings;